import copy

original_list = [1, 2, [3]]

print("")
print("Original list: " + str(original_list))
print("")
print("Adding another reference")
reference = original_list
print("")
print("Original list: " + str(original_list))
print("2nd reference: " + str(reference))
print("")
print("Making a SHALLOW copy")
shallow_copy = copy.copy(original_list)
print("")
print("Original list: " + str(original_list))
print("2nd reference: " + str(reference))
print("Shallow copy: " + str(shallow_copy))
print("")
print("Altering the SHALLOW copy (modifying the nested list in the copy)")
shallow_copy[2].append(4)
print("")
print("Original list: " + str(original_list))
print("2nd reference: " + str(reference))
print("Shallow copy: " + str(shallow_copy))
print("")

print("Changing the original list")
original_list[2].append(6)
print("")
print("Original list: " + str(original_list))
print("2nd reference: " + str(reference))
print("Shallow copy: " + str(shallow_copy))
print("")
