
# I could totally do all the building with makefile , but I want us to keep honing our Bash skills.
# Plus , you probably don't even know how makefile works , so here's your chance to get some understanding of that. 

#
