STACK SEGMENT PARA STACK
	DB 64 DUP (' ')
STACK ENDS
	
DATA SEGMENT PARA 'DATA'
DATA ENDS

CODE SEGMENT PARA 'CODE'

	MAIN PROC FAR
		MOV AH, 00H		; SET VIDEO MODE (UNDER INT 10H). 
		MOV AL, 13H		; VIDEO MODE 320 X 200 X 256. 
		INT 10H
		
		MOV AH, 0BH		; FOCUS ON COLORS (UNDER INT 10H)
		MOV BH, 00H		; TO BACKGROUND COLOR (GFX) OR BORDER COLOR (TEXT). 
		MOV BL, 00H		; AND CHOOSE COLOR - BLACK. 
		INT 10H
		
		MOV AH, 0CH		; FXN: WRITE A PIXEL. (AL = COLOR, BH = PAGE NO., CX = X, DX = Y.)
		MOV AL, 0FH		; WHITE. 
		MOV BH, 00H		; PAGE 0 BY DEFAULT. 
		MOV CX, 120
		MOV DX, 100
		INT 10H
		
		MOV AH, 00H		; READ KEYPRESS. 
		INT 16H
		MOV AH, 00H		; BACK TO TEXT. 
		MOV AL, 03H
		INT 10H
		MOV AH, 4CH		; TERM PER DOS. 
		INT 21H
		
		
		RET
	MAIN ENDP
	
CODE ENDS
END