STACK SEGMENT PARA STACK
	DB 64 DUP (' ')
STACK ENDS
	
DATA SEGMENT PARA 'DATA'
	BALL_X DW 0AH	; 16 BITS
	BALL_Y DW 0AH
DATA ENDS

CODE SEGMENT PARA 'CODE'

	MAIN PROC FAR	
		; RANDOM TRASH IS SPEWED BECAUSE DS IS NOT REACHED. 
		; NEED TO TELL WHERE TO-BE-USED VARIABLES ARE. 
	ASSUME CS:CODE, DS:DATA, SS:STACK	; ? PROBABLY ALIASES THAT NEED TO BE TIED TO REGS. 
	PUSH DS								; ?
	SUB AX, AX							; CAN'T YOU JUST MOV AX,0 ?
	PUSH AX								; ? 
	MOV AX, DATA						; 
	MOV DS, AX							; POINT DS TO DATA VARS. 
	POP AX								; ? CLEARING THE STACK CONTENT TO THE WIND ? 
	POP AX								; 
	
		MOV AH, 00H		; SET VIDEO MODE (UNDER INT 10H). 
		MOV AL, 13H		; VIDEO MODE 320 X 200 X 256. 
		INT 10H
		
		MOV AH, 0BH		; FOCUS ON COLORS (UNDER INT 10H)
		MOV BH, 00H		; TO BACKGROUND COLOR (GFX) OR BORDER COLOR (TEXT). 
		MOV BL, 00H		; AND CHOOSE COLOR - BLACK. 
		INT 10H
		
		MOV AH, 0CH		; FXN: WRITE A PIXEL. (AL = COLOR, BH = PAGE NO., CX = X, DX = Y.)
		MOV AL, 0FH		; WHITE. 
		MOV BH, 00H		; PAGE 0 BY DEFAULT. 
		MOV CX, BALL_X	; 16 BITS. 
		MOV DX, BALL_Y
		INT 10H
		
		MOV AH, 00H		; READ KEYPRESS. 
		INT 16H
		MOV AH, 00H		; BACK TO TEXT. 
		MOV AL, 03H
		INT 10H
		MOV AH, 4CH		; TERM PER DOS. 
		INT 21H
		
		
		RET
	MAIN ENDP
	
CODE ENDS
END